name: "Build and push my toolbox image"

permissions: read-all

on:
  push:
    branches:
      - main
    paths:
      - .
  schedule:
    - cron:  '0 0 * * MON'

jobs:
  build-and-push-images:
    name: Build and push images

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker.io
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_IO_USERNAME }}
          password: ${{ secrets.DOCKER_IO_TOKEN }}

      - name: Build and push my toolbox image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Containerfile
          platforms: linux/amd64
          push: true
          no-cache: true
          tags: docker.io/${{ github.repository }}:latest
